services:
  app:
    build:
      context: .
    env_file:
      - ./local.env
    ports:
      - "${FRONTPORT}:3000"
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    # command: sh -c "npm run dev"
    networks:
      - default
      - snowboard_default #snowboadコンテナのネットワーク名
volumes:
  node_modules:
networks:
  snowboard_default:
    external: true