version: "3.8"
services:
  app:
    # env_file: # ビルド時にはこのファイルで指定した環境変数を読み込まない
    #   - local.env
    build:
      context: .
      dockerfile: Dockerfile
      target: build
    ports:
      - "${FRONT_PORT}:3000"
      - "${MOCK_PORT}:3001"
    volumes:
      - .:/app
      - node_modules:/app/node_modules # node_modules は git管理のため volume でマウント
    command: sh -c "npm run dev && npm json-server"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001"]
      interval: 3s
      timeout: 10s
      retries: 10
    # networks:
    #   - default
    #   - snowboard_default #snowboadコンテナのネットワーク名
volumes:
  node_modules:
# networks:
#   snowboard_default:
#     external: true
